import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  sortMenuIsVisible: false,
  filterMenuIsVisible: false
};

export const appSlice = createSlice({
    name: 'app',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
      openSortMenu: (state) => {
        state.sortMenuIsVisible = true
      },
      closeSortMenu: (state) => {
        state.sortMenuIsVisible = false
      },
      toggleSortMenu: (state) => {
        state.sortMenuIsVisible = !state.sortMenuIsVisible
      },
      openFilterMenu: (state) => {
        state.filterMenuIsVisible = true
      },
      closeFilterMenu: (state) => {
        state.filterMenuIsVisible = false
      },
      toggleFilterMenu: (state) => {
        state.filterMenuIsVisible = !state.filterMenuIsVisible
      },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
    },
  });

export const { 
  openSortMenu, closeSortMenu, toggleSortMenu,
  openFilterMenu, closeFilterMenu, toggleFilterMenu } = appSlice.actions

export const isSortMenuOpen = (state) => state.app.sortMenuIsVisible
export const isFilterMenuOpen = (state) => state.app.filterMenuIsVisible

export default appSlice.reducer;